# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59fa5dac725e14b0d55d38f62f1918f09b5a8d89309de5d5cc305d2413d40b61f1484b4064d2fae56dc7e5ab53a094030f55058a99dcca27e7c67cce8e59e4f6

test:
  secret_key_base: 9c28b4a570e6c19a565e5d2309f12209d069a2ad14cbb103525b56dd3878b375458baef6fba24bf540e777ad3fb0f4f511a7e0dc9c5e4a80df73688184d8601e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
